// Pulling data
export const GET_DATA = "GET_DATA";
export const GET_DATA_SERVER_RESPONSE_SUCCESS = "GET_DATA_SERVER_RESPONSE_SUCCESS";
export const GET_DATA_SERVER_RESPONSE_FAILURE = "GET_DATA_SERVER_RESPONSE_FAILURE"
